import os
import zipfile
import io

ZIP_PATH = os.path.join(os.path.expanduser("~"), "Desktop", "PixelOrchestrator_Enterprise.zip")
zip_buffer = io.BytesIO()

with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zipf:
    def add_file(arcname, content):
        zipf.writestr(arcname, content)

    # Core modules (simplified but working)
    add_file("core/__init__.py", "")
    add_file("core/command_result.py", "from dataclasses import dataclass\n@dataclass\nclass CommandResult:\n    success: bool\n    stdout: str\n    stderr: str\n    returncode: int\n    duration: float\n    command: str = None\n")
    add_file("core/exceptions.py", "class PixelToolkitError(Exception): pass\nclass DeviceNotFoundError(PixelToolkitError): pass\nclass FastbootTimeoutError(PixelToolkitError): pass\nclass AdbTimeoutError(PixelToolkitError): pass\nclass UnsupportedStateError(PixelToolkitError): pass\nclass ExecutableNotFoundError(PixelToolkitError): pass\nclass PartitionNotFoundError(PixelToolkitError): pass\nclass ImageFileError(PixelToolkitError): pass\nclass RollbackBlockedError(PixelToolkitError): pass\nclass DeviceStateError(PixelToolkitError): pass\n")
    add_file("core/logger.py", "import logging, sys\ndef setup_logger(name='pixel_toolkit', level=logging.INFO):\n    logger = logging.getLogger(name)\n    logger.setLevel(level)\n    logger.propagate = False\n    if not logger.handlers:\n        handler = logging.StreamHandler(sys.stdout)\n        handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))\n        logger.addHandler(handler)\n    return logger\n_logger = setup_logger()\ndef get_logger(): return _logger\n")
    add_file("core/transport.py", "import subprocess, time, shutil, os, threading\nfrom pathlib import Path\nfrom typing import List, Optional\nfrom .command_result import CommandResult\nfrom .exceptions import ExecutableNotFoundError\nfrom .logger import get_logger\nlogger = get_logger()\nclass Transport:\n    def __init__(self, platform_tools_path: Optional[str] = None):\n        self.adb_path = self._find_executable('adb', platform_tools_path)\n        self.fastboot_path = self._find_executable('fastboot', platform_tools_path)\n    def _find_executable(self, name, custom_path):\n        if custom_path:\n            candidate = Path(custom_path) / name\n            if candidate.is_file(): return str(candidate)\n            if os.name=='nt' and not candidate.suffix:\n                candidate = candidate.with_suffix('.exe')\n                if candidate.is_file(): return str(candidate)\n        which = shutil.which(name)\n        if which: return which\n        bundled = Path('./platform-tools') / (name + ('.exe' if os.name=='nt' else ''))\n        if bundled.is_file(): return str(bundled)\n        raise ExecutableNotFoundError(f'{name} not found.')\n    def _run(self, cmd, timeout=30):\n        start = time.time()\n        proc = None\n        try:\n            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, encoding='utf-8', errors='replace', shell=False)\n            def kill_proc():\n                if proc.poll() is None: proc.terminate()\n            timer = threading.Timer(timeout, kill_proc)\n            timer.start()\n            stdout, stderr = proc.communicate()\n            timer.cancel()\n            return CommandResult(success=proc.returncode==0, stdout=stdout.strip(), stderr=stderr.strip(), returncode=proc.returncode, duration=time.time()-start, command=' '.join(cmd))\n        except Exception as e:\n            if proc: proc.terminate()\n            return CommandResult(success=False, stdout='', stderr=str(e), returncode=-1, duration=time.time()-start, command=' '.join(cmd))\n    def adb(self, args, timeout=30): return self._run([self.adb_path]+args, timeout)\n    def fastboot(self, args, timeout=30): return self._run([self.fastboot_path]+args, timeout)\n")
    add_file("core/adb_manager.py", "from typing import List, Tuple, Optional\nfrom .transport import Transport\nclass AdbManager:\n    def __init__(self, transport):\n        self.transport = transport\n        self._ensure_server()\n    def _ensure_server(self):\n        self.transport.adb(['start-server'], timeout=10)\n    def devices(self):\n        res = self.transport.adb(['devices'])\n        devices = []\n        for line in res.stdout.splitlines():\n            if line.startswith('* daemon') or not line.strip() or line.startswith('List of devices'): continue\n            parts = line.split()\n            if len(parts)>=2: devices.append((parts[0], parts[1]))\n        return devices\n    def shell(self, command, serial=None, timeout=30):\n        args = []\n        if serial: args += ['-s', serial]\n        args += ['shell', command]\n        return self.transport.adb(args, timeout=timeout)\n    def get_prop(self, prop, serial=None):\n        res = self.shell(f'getprop {prop}', serial=serial, timeout=5)\n        return res.stdout.strip() if res.success and res.stdout else None\n    def reboot(self, target='', serial=None):\n        args = []\n        if serial: args += ['-s', serial]\n        args += ['reboot']\n        if target: args.append(target)\n        return self.transport.adb(args, timeout=10)\n")
    add_file("core/fastboot_manager.py", "from typing import Optional, List\nfrom .transport import Transport\nclass FastbootManager:\n    def __init__(self, transport):\n        self.transport = transport\n    def devices(self):\n        res = self.transport.fastboot(['devices'])\n        return [line.split()[0] for line in res.stdout.splitlines() if line.strip()] if res.success else []\n    def getvar(self, var, serial=None):\n        args = ['getvar', var]\n        if serial: args = ['-s', serial] + args\n        res = self.transport.fastboot(args)\n        combined = res.stdout + '\\n' + res.stderr\n        for line in combined.splitlines():\n            if f'({var}):' in line or f' {var}:' in line:\n                parts = line.split(':',1)\n                if len(parts)==2: return parts[1].strip()\n        return None\n")
    add_file("core/device_state.py", "from enum import Enum\nfrom typing import Optional, Tuple\nfrom .adb_manager import AdbManager\nfrom .fastboot_manager import FastbootManager\nclass DeviceState(Enum):\n    DISCONNECTED='disconnected'; ADB='adb'; RECOVERY='recovery'; SIDELOAD='sideload'; FASTBOOT='fastboot'; FASTBOOTD='fastbootd'; EDL='edl'\nclass DeviceDetector:\n    def __init__(self, adb, fastboot):\n        self.adb=adb; self.fastboot=fastboot\n    def detect_state(self, serial=None):\n        for s,state in self.adb.devices():\n            if serial and s!=serial: continue\n            if state=='device':\n                mode=self.adb.get_prop('ro.bootmode',serial=s)\n                if mode=='recovery': return DeviceState.RECOVERY,s\n                elif mode=='sideload': return DeviceState.SIDELOAD,s\n                else: return DeviceState.ADB,s\n            elif state=='recovery': return DeviceState.RECOVERY,s\n            elif state=='sideload': return DeviceState.SIDELOAD,s\n        fb=self.fastboot.devices()\n        if fb:\n            first=fb[0]\n            if serial and serial not in fb: return DeviceState.DISCONNECTED,None\n            is_fastbootd = self.fastboot.getvar('is-userspace',first) == 'yes'\n            return DeviceState.FASTBOOTD if is_fastbootd else DeviceState.FASTBOOT, first\n        return DeviceState.DISCONNECTED,None\n")
    # Main GUI
    add_file("main_gui.py", "import sys\nfrom PySide6.QtWidgets import QApplication, QLabel, QVBoxLayout, QWidget\nfrom core.transport import Transport\nfrom core.adb_manager import AdbManager\nfrom core.device_state import DeviceDetector\nfrom core.fastboot_manager import FastbootManager\nclass MainWindow(QWidget):\n    def __init__(self):\n        super().__init__()\n        self.setWindowTitle('Pixel Orchestrator Enterprise')\n        self.resize(500,300)\n        layout = QVBoxLayout()\n        self.label = QLabel('Initializing...')\n        layout.addWidget(self.label)\n        self.setLayout(layout)\n        self.init_backend()\n    def init_backend(self):\n        transport = Transport()\n        adb = AdbManager(transport)\n        fastboot = FastbootManager(transport)\n        detector = DeviceDetector(adb, fastboot)\n        state, serial = detector.detect_state()\n        self.label.setText(f'Device State: {state.value}\\nSerial: {serial or \\'None\\'}\\n\\nEnterprise Edition Ready.')\napp = QApplication(sys.argv)\nwin = MainWindow()\nwin.show()\nsys.exit(app.exec())\n")
    add_file("requirements.txt", "PySide6>=6.5\n")
    add_file("README.md", "# Pixel Orchestrator Enterprise\nExtract, run `pip install -r requirements.txt`, then `python main_gui.py`\n")

with open(ZIP_PATH, "wb") as f:
    f.write(zip_buffer.getvalue())

print(f"✅ Enterprise ZIP created at: {ZIP_PATH}")
print("\nNext steps:")
print("1. Extract the ZIP")
print("2. pip install -r requirements.txt")
print("3. python main_gui.py")