"""
Restore Engine – Manifest‑based Recovery
- Reads backup manifest generated by BackupEngine
- Verifies image integrity before flashing
- Restores partitions using fastboot (or ADB dd for legacy)
- Supports slot‑aware restore
"""

import os
import json
import hashlib
import time
from typing import List, Optional
from dataclasses import dataclass

from .state_orchestrator import StateOrchestrator
from .device_state import DeviceState
from .logger import log_event
from .event_bus import event_bus, Event, EventType

@dataclass
class RestoreResult:
    device_serial: str
    restored: List[str]
    failed: List[str]
    skipped: List[str] = None

class RestoreEngine:
    def __init__(self, orchestrator: StateOrchestrator):
        self.orchestrator = orchestrator
        self.dry_run = False
        self._verify_before_restore = True

    def restore_from_manifest(
        self,
        manifest_path: str,
        slot: Optional[str] = None,
        verify: bool = True
    ) -> RestoreResult:
        """
        Restore partitions from a backup manifest.
        Returns RestoreResult with lists of restored/failed partitions.
        """
        if not os.path.isfile(manifest_path):
            raise FileNotFoundError(f"Manifest not found: {manifest_path}")

        with open(manifest_path, "r") as f:
            data = json.load(f)

        snap = self.orchestrator.snapshot()
        serial = snap.serial
        if not serial:
            raise Exception("No device connected")

        # Ensure device is in flashable state (fastboot / fastbootd)
        if snap.state not in (DeviceState.FASTBOOT, DeviceState.FASTBOOTD):
            log_event(serial, "restore", "INFO", "Device not in fastboot, transitioning...")
            self.orchestrator.safe_transition(DeviceState.FASTBOOT, serial=serial)
            snap = self.orchestrator.snapshot(force_refresh=True)

        restored = []
        failed = []
        skipped = []
        manifest_dir = os.path.dirname(manifest_path)

        for item in data.get("items", []):
            full_name = item.get("full_name", "")
            expected_sha = item.get("sha256", "")
            image_file = item.get("image_path", "")

            # Resolve image path (absolute or relative to manifest)
            if not os.path.isabs(image_file):
                image_file = os.path.join(manifest_dir, os.path.basename(image_file))

            if not os.path.isfile(image_file):
                log_event(serial, "restore", "ERROR", f"Image not found: {image_file}")
                failed.append(full_name)
                continue

            # Verify SHA256
            if verify and self._verify_before_restore:
                try:
                    actual_sha = self._compute_sha256(image_file)
                    if actual_sha != expected_sha:
                        log_event(serial, "restore", "ERROR", f"SHA256 mismatch for {full_name}")
                        failed.append(full_name)
                        continue
                except Exception as e:
                    log_event(serial, "restore", "ERROR", f"Hash verification failed: {e}")
                    failed.append(full_name)
                    continue

            # Resolve partition (strip slot suffix if needed)
            logical_name = full_name.split('_')[0]  # e.g., "boot_a" -> "boot"
            part = snap.partitions.get_by_logical(logical_name, slot)
            if not part:
                log_event(serial, "restore", "WARNING", f"Partition {logical_name} not found, skipping")
                skipped.append(full_name)
                continue

            target = part.full_name()
            if self.dry_run:
                log_event(serial, "restore", "INFO", f"[DRY RUN] Would restore {target}")
                restored.append(full_name)
                continue

            # Perform restore via fastboot flash
            log_event(serial, "restore", "INFO", f"Restoring {target} from {image_file}")
            success = self.orchestrator.flash(serial, target, image_file)
            if success:
                restored.append(full_name)
                event_bus.emit(Event(EventType.OPERATION_END, {
                    "operation": "restore",
                    "partition": target,
                    "success": True
                }, source="restore_engine"))
            else:
                failed.append(full_name)
                event_bus.emit(Event(EventType.ERROR, {
                    "operation": "restore",
                    "partition": target,
                    "error": "Flash failed"
                }, source="restore_engine"))
                log_event(serial, "restore", "ERROR", f"Failed to restore {target}")

        result = RestoreResult(serial, restored, failed, skipped)
        log_event(serial, "restore", "INFO",
                  f"Restore completed: restored {len(restored)}, failed {len(failed)}, skipped {len(skipped)}")
        return result

    def _compute_sha256(self, file_path: str) -> str:
        sha256 = hashlib.sha256()
        with open(file_path, "rb") as f:
            while chunk := f.read(1024 * 1024):
                sha256.update(chunk)
        return sha256.hexdigest()

    def set_dry_run(self, enabled: bool):
        self.dry_run = enabled

    def enable_verification(self, enabled: bool):
        self._verify_before_restore = enabled